-- ========================================================
-- ESQUEMA ANDE_CDSS - PostgreSQL
-- ========================================================



-- =========================================
-- 1. TIPOS ENUM Y CONFIGURACIÓN INICIAL
-- =========================================

CREATE TYPE clase_usuario AS ENUM (
    'ADMIN SISTEMA',
    'ADMIN',
    'VALIDADOR',
    'EDIT',
    'READ ONLY'
);


-- =========================================
-- 2. USUARIOS Y SESIONES
-- =========================================

-- Entidad: Usuario
CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY,

    username VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    user_password VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT FALSE,
    rol clase_usuario NOT NULL DEFAULT 'EDIT',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuario_username UNIQUE (username),
    CONSTRAINT uq_usuario_email UNIQUE (email)
);
-- Trigger para mantener actualizado 'updated_at' en usuario
CREATE OR REPLACE FUNCTION actualizar_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_usuario_updated_at
BEFORE UPDATE ON usuario
FOR EACH ROW
EXECUTE FUNCTION actualizar_updated_at();


-- Entidad: Sesiones de Usuario
CREATE TABLE sesiones_usuario (
    id_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario INTEGER,
    fecha_login TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_logout TIMESTAMP,
    ip VARCHAR(45), -- Soporta IPv4 e IPv6
    user_agent TEXT,
    resultado_login BOOLEAN NOT NULL DEFAULT TRUE,
    motivo_error VARCHAR(255),

    CONSTRAINT pk_sesion_usuario PRIMARY KEY (id_sesion),
    CONSTRAINT fk_sesion_usuario_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE SET NULL
);



-- =========================================
-- 3. AUDITORÍA Y LOGS
-- =========================================

-- Entidad: Auditoría de Cambios de Datos
CREATE TABLE auditoria_evento (
    id_auditoria INTEGER GENERATED ALWAYS AS IDENTITY,
    tabla_afectada VARCHAR(100) NOT NULL,
    id_registro INTEGER NOT NULL,
    accion VARCHAR(10) NOT NULL, -- INSERT, UPDATE, DELETE
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    id_usuario INTEGER,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_auditoria_evento PRIMARY KEY (id_auditoria),
    CONSTRAINT fk_auditoria_evento_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

-- Función de Auditoría (Triggers)
CREATE OR REPLACE FUNCTION generar_auditoria() RETURNS TRIGGER AS $$
DECLARE
    v_id_usuario INTEGER;
    v_id_registro INTEGER;
    v_pk_name TEXT;
BEGIN
    -- 1. Intentar obtener el ID del usuario desde una variable de sesión
        -- hay que cambiar esto para que reciba el usuario del backend, no es el usuario de posgres
    BEGIN
        v_id_usuario := current_setting('app.current_user_id')::integer;
    EXCEPTION WHEN OTHERS THEN
        v_id_usuario := NULL;
    END;

    -- 2. Obtener el nombre de la PK desde el argumento del trigger
    v_pk_name := TG_ARGV[0];

    -- 3. Lógica según la operación
    IF (TG_OP = 'UPDATE') THEN
        v_id_registro := (to_jsonb(OLD) ->> v_pk_name)::integer;
        INSERT INTO auditoria_evento (tabla_afectada, id_registro, accion, datos_anteriores, datos_nuevos, id_usuario)
        VALUES (TG_TABLE_NAME, v_id_registro, 'UPDATE', to_jsonb(OLD), to_jsonb(NEW), v_id_usuario);
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        v_id_registro := (to_jsonb(OLD) ->> v_pk_name)::integer;
        INSERT INTO auditoria_evento (tabla_afectada, id_registro, accion, datos_anteriores, id_usuario)
        VALUES (TG_TABLE_NAME, v_id_registro, 'DELETE', to_jsonb(OLD), v_id_usuario);
        RETURN OLD;
    ELSIF (TG_OP = 'INSERT') THEN
        v_id_registro := (to_jsonb(NEW) ->> v_pk_name)::integer;
        INSERT INTO auditoria_evento (tabla_afectada, id_registro, accion, datos_nuevos, id_usuario)
        VALUES (TG_TABLE_NAME, v_id_registro, 'INSERT', to_jsonb(NEW), v_id_usuario);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;


-- Entidad: Registro de Errores del Backend (Logs)
CREATE TABLE errores_backend (
    id_error INTEGER GENERATED BY DEFAULT AS IDENTITY,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nivel VARCHAR(50) NOT NULL, -- ERROR, WARNING, INFO
    modulo VARCHAR(255),
    endpoint VARCHAR(255),
    mensaje TEXT NOT NULL,
    stack_trace TEXT,
    id_usuario INTEGER,
    id_sesion INTEGER,

    CONSTRAINT pk_errores_backend PRIMARY KEY (id_error),
    CONSTRAINT fk_errores_backend_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    CONSTRAINT fk_errores_backend_sesion_usuario FOREIGN KEY (id_sesion) REFERENCES sesiones_usuario(id_sesion) ON DELETE SET NULL
);